### ISSUE TITLE
YAML Support

### ISSUE THREAD

**Issue by Templarian** [lukas-tr/vscode-materialdesignicons-intellisense#1]
You may have noticed on twitter there is a large user base for Home Assistant. I'm working on linking your extension in the documentation in a few places and realized it would be very beneficial.

If you could by chance get it to work with YAML. For instance:

```yaml
icon: mdi:account-circle
```

MDI is their default icon font for their platform.

https://www.home-assistant.io/docs/configuration/customizing-devices/

No problem if this is out of scope.

**Comment by lukas-tr** [comment]
I added support for Home Assistant icon names along with some other changes.

- Add `homeAssistant` to `materialdesigniconsIntellisense.insertStyle`
- Provide completions for Home Assistant icon names
- Provide lint for Home Assistant icon names
- Provide hover preview for Home Assistant icon names
- Suggest completions when pressing <kbd>ctrl</kbd> + <kbd>space</kbd> even when the last character is not `i`, `-` or `:`
- Delete already existing text after inserting snippet (previously, typing `mdi-acc` + <kbd>enter</kbd> would result in `mdi-mdi-account` in `.js` files, now results in `mdi-account`)
- Set `materialdesigniconsIntellisense.insertPrefix`'s default value to `""`

**Comment by Templarian** [comment]
@lukas-tr https://twitter.com/home_assistant/status/1105582243014234112 I think they like it. 😃

**Comment by Templarian** [comment]
Going to close this issue out since it appears to be live now.
