### ISSUE TITLE
error after installing the docker version

### ISSUE THREAD

**Issue by abeksis** [lukas-tr/vscode-materialdesignicons-intellisense#10]
[lukas-tr.materialdesignicons-intellisense]: property `title` is mandatory and must be of type `string` or `object`

I get this error after installing the docker version

**Comment by lukas-tr** [comment]
Could you execute `Developer: Show Running Extensions`, right click `Material Design Icons Intellisense` and choose `Report Issue` from the context menu?

**Comment by abeksis** [comment]
i cant see what you told me to do maybe is it in another toolbar?

**Comment by lukas-tr** [comment]
<kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>P</kbd> or <kbd>F1</kbd> and type `Developer: Show Running Extensions`
