### ISSUE TITLE
No preview window

### ISSUE THREAD

**Issue by puzz3d** [lukas-tr/vscode-materialdesignicons-intellisense#12]
I can see no preview window, though the "hover" feature works fine.

VS code: Version: 1.44.2 (system setup)
OS: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/64879167/81132776-3b1ef500-8f58-11ea-9dfd-d9f4a69862a2.png)

**Comment by lukas-tr** [comment]
The intellisense preview can be toggled with <kbd>Ctrl</kbd> + <kbd>Space</kbd> by default.
You can also find the shortcut via `Preferences: Open Keyboard Shortcuts` and searching for `toggleSuggestionDetails`.

**Comment by Ares9323** [comment]
I am having the same problem, something changed with the latest vscode update.
As you can see from my image some icons are displayed, others are not (the ones in the red box) and they have a different icon before the name.

![image](https://user-images.githubusercontent.com/46932745/81225340-5ede4b80-8fe9-11ea-9b54-c975b28a8b5a.png)

**Comment by puzz3d** [comment]
> The intellisense preview can be toggled with Ctrl + Space by default.

Thank you, Ctrl + Space works.
Shouldn't it be in the readme file?

**Comment by Ares9323** [comment]
> > The intellisense preview can be toggled with Ctrl + Space by default.
> 
> Thank you, Ctrl + Space works.
> Shouldn't it be in the readme file?

It's the standard shortcut in VScode for turning autocompletion on, unfortunately in my case it doesn't work, I'm happy if you solved your problems, unfortunately I can't say the same:
I tried to reinstall the extension, now I'm having name duplicates and some of them don't work..
![image](https://user-images.githubusercontent.com/46932745/81233438-f9915700-8ff6-11ea-84c7-11104dc7bedd.png)

**Comment by lukas-tr** [comment]
Yes, I'll add it
