### ISSUE TITLE
Some Icons changed name in mdi v5.1.45 and new ones are present

### ISSUE THREAD

**Issue by Ares9323** [lukas-tr/vscode-materialdesignicons-intellisense#13]
Hi, today I started a new laravel project and I noticed the "mdi-settings" icon is now called "mdi-cog", i think others may have changed and there are 100 new icons as you can see [here](https://cdn.materialdesignicons.com/5.1.45/).

Are you going to update the extension or releasing another version for backward compatibility?
Do you have an automated system to include new icons or do you need help doing it? If you need some help you can explain me what to do and I'll send you a pull request 😉

Thank you, have a nice day!

**Comment by lukas-tr** [comment]
An automated system would be perfect. I have two ideas of how to implement it:

- Option 1: The `@mdi/svg` package is watched and a new version of the extension is built and published using a ci/cd provider with the latest `@mdi/svg` bundled.
- Option 2: `@mdi/svg` is removed as dependency and is instead downloaded by the extension when a new version releases. 

I think option 2 is more flexible as this would allow users to choose the version they want to work with. 

Thanks for the offer, but I can do it myself and there are many other great projects that need help more than I do.

**Comment by Ares9323** [comment]
Yeah both ideas are good, I was thinking to look inside the node_modules workspace folder to make the extension work in projects with different versions of mdi.
Unfortunately there is no svg folder in my node_modules/@mdi, there's only the font folder so I don't think this solution is possible if svg files are needed.

Another thing I was asking myself is if the alias system is something you made or it's provided by mdi directly, because it would be very bad to lose it with automation.
![image](https://user-images.githubusercontent.com/46932745/81805982-1b6d6b00-951c-11ea-9e35-53a15916cd49.png)
Icons are pretty difficult to find in the official cheatsheet, I really love aliases <3

Thanks for the fast answer 😊

**Comment by lukas-tr** [comment]
I didn't create the aliases. They are found inside `node_modules/@mdi/svg/meta.json`. The cheat sheet doesn't have them but the main page (https://materialdesignicons.com/) uses them when searching. 
![image](https://user-images.githubusercontent.com/36337818/81810481-4e672d00-9523-11ea-8f0e-6827d6769b54.png)

I also can't count on users having npm installed. I will have to use the npm api directly to get all versions and download and extract the `@mdi/svg` package somewhere. 

Looking inside `node_modules` would still be a good idea as I could automatically detect the right version to use.

**Comment by Ares9323** [comment]
Thank you for the tip, I didn't know about the "smart search"!

**Comment by lukas-tr** [comment]
You can now switch between versions manually or set it to always use the latest release.

![Switching between versions](https://raw.githubusercontent.com/lukas-tr/vscode-materialdesignicons-intellisense/master/doc/change-mdi-version.gif)

**Comment by Ares9323** [comment]
Wonderful result, thanks!
