### ISSUE TITLE
Sir, do you have any plan to support Flutter's Icon Widget?

### ISSUE THREAD

**Issue by zhengger** [lukas-tr/vscode-materialdesignicons-intellisense#14]
Your extension is amazing good.
Thanks.

**Comment by lukas-tr** [comment]
Yes, I will add support for flutter.

**Comment by lukas-tr** [comment]
I found 2 different libraries for flutter (mdi and material_design_icons_flutter) and added support for both. 
Suggestions can be triggered with `Mdi.`, `MdiIcons.` and `MdiIcons.fromString('`. Inserting from the MDI Explorer, hovers and decorations also work.

![Decoration](https://raw.githubusercontent.com/lukas-tr/vscode-materialdesignicons-intellisense/master/doc/decoration.png)

**Comment by Ares9323** [comment]
@zhengger can you please post an example of what you can do with flutter icons?
I tried to understand what they are when you opened this issue but still I have no idea!
Thank you in advance!

**Comment by lukas-tr** [comment]
@Ares9323 Both libraries have examples: https://pub.dev/packages/material_design_icons_flutter#usage https://pub.dev/packages/mdi#usage
