### ISSUE TITLE
The insertPrefix setting was useful, is it going to come back in the future?

### ISSUE THREAD

**Issue by Ares9323** [lukas-tr/vscode-materialdesignicons-intellisense#15]
Today I opened up my settings.json again and I noticed that my setting "materialdesigniconsIntellisense.insertPrefix": "mdi ", was disabled (I noticed it months ago but I hoped it would have come back one day).

It was really useful to me, because I used to type "mdi-something" and when I pressed Enter the result was "mdi mdi-something", now I have to type mdi two times (it's not that hard I admit it but it would be cool to have something like a snippet)

If there's a prefix/suffix possibility you could set for example:

`"materialdesigniconsIntellisense.insertPrefix":"<i class=\"mdi"`,
`"materialdesigniconsIntellisense.insertSuffix":"\"></i>"`,

..to create a working icon pressing just a few keys, in this case:
`<i class="mdi mdi-something"></i>`

Thanks for you time and your work, have a nice day

**Comment by lukas-tr** [comment]
Possibly, but I don't know when I have time to work on this.

**Comment by lukas-tr** [comment]
This works slightly different now ([example](https://github.com/lukas-tr/vscode-materialdesignicons-intellisense#how-to-add-support-for-other-libraries)). The prefix will be inserted before anything matched by the regex in `match`.
