### ISSUE TITLE
[FR]: support for iconmoon fonts

### ISSUE THREAD

**Issue by farfromrefug** [lukas-tr/vscode-materialdesignicons-intellisense#16]
It might be a bit out of the subjeft. But i love your plugin especially the auto completion and preview in code.
Now i often use my custom fonts created with icomoon. I kind of dream to be able to use them with your plugin.
Do you think that would be foreseeable ?
I am thinking that by giving a couple scss/font path it could be doable?

**Comment by lukas-tr** [comment]
It should be doable, but I think it's out of scope of this plugin.
