### ISSUE TITLE
Trying to make a custom matcher for React Native Vector Icon

### ISSUE THREAD

**Issue by kuasha420** [lukas-tr/vscode-materialdesignicons-intellisense#17]
Hello

I'm truing to match the following format but so far having partial success with it. 

<Icon name="{param}"

and 

icon="{param}" 

```json
{
      "match": "\\bname\\=\"{param}\"\\b",
      "insert": "{param}",
      "displayName": "React Native Vector Icon",
      "name": "rnvec"
    },
    {
      "match": "\\bicon\\=\"{param}\"\\b",
      "insert": "{param}",
      "displayName": "React Native Icon Props",
      "name": "rnicon"
    }
```

I can get the intelisense but the little preview icon in the left side is not working.

Help would be greatly appreciated!

**Comment by lukas-tr** [comment]
Is just the preview on the left not working or does the hover preview also not show up?

**Comment by kuasha420** [comment]
@lukas-tr The hover preview also doesn't show up. Only intelisense works

**Comment by lukas-tr** [comment]
`\b` matches word boundaries (a `\w` followed/preceded by a `\W` character). Remove the `\b` at the end and your're good. 

```json
        {
            "match": "\\bname\\=\"{param}\"",
            "insert": "{param}",
            "displayName": "React Native Vector Icon",
            "name": "rnvec"
        },
        {
            "match": "\\bicon\\=\"{param}\"",
            "insert": "{param}",
            "displayName": "React Native Icon Props",
            "name": "rnicon"
        }
```

**Comment by kuasha420** [comment]
@lukas-tr  Thanks a bunch!
