### ISSUE TITLE
Stuck on Code Actions

### ISSUE THREAD

**Issue by mrhammadasif** [lukas-tr/vscode-materialdesignicons-intellisense#18]
<img width="547" alt="Screenshot 2020-11-18 at 2 30 19 PM" src="https://user-images.githubusercontent.com/1535613/99511940-b99a2c00-29aa-11eb-9024-dea3052b4a86.png">

When enabled in Vuetify Project. (tested in empty vuetify project, as well)

It kind of take too much time on code actions, I have also tried to disable Vetur but that causes Vue files to not being detected

**Comment by lukas-tr** [comment]
Does this still show up when 
`materialdesigniconsIntellisense.enableLinter` is `false` or when this extension is disabled?

If not, a list of extensions you have installed and the steps for creating the project and getting this message would be helpful.

**Comment by mrhammadasif** [comment]
using `materialdesigniconsIntellisense.enableLinter` fixed the issue.

I think linter is causing issue then, shouldn't it be disabled by default?

**Comment by lukas-tr** [comment]
I tested the linter with both vetur and eslint installed, but I didn't encounter any issues with code actions. 
Do you have additional extensions installed? Does this occur only in specific files/all vue files/specific projects?

**Comment by lukas-tr** [comment]
Lately I've been getting similar notifications (also Vetur, Eslint and my extension). It's not stuck, but takes 30+ seconds until it's done. 

The corresponding svg file will be read from disk each time an icon preview is generated, which might slow things down. In the next version, all icon data will be kept in memory.
