### ISSUE TITLE
Changes icon size for inline decorations

### ISSUE THREAD

**Issue by ErickPetru** [lukas-tr/vscode-materialdesignicons-intellisense#19]
Currently, `materialdesigniconsIntellisense.iconSize` is used for intellisense and hover. I suppose it could be very misleading to use the same value for controlling decorations inline in the code.

But the impossibility to customize it is also annoying, especially when we have custom font sizes and line heights for our code and the decorator shown becomes incompatible with that.

So, what about a new setting, like `materialdesigniconsIntellisense.decorationSize`?

**Comment by lukas-tr** [comment]
I added following new settings: 

- `materialdesigniconsIntellisense.decoration.size`: Set decoration width and height
- `materialdesigniconsIntellisense.decoration.margin`: Set decoration margin
