### ISSUE TITLE
Add a icon for when the Explorer is moved to the sidebar

### ISSUE THREAD

**Issue by henriquecm** [lukas-tr/vscode-materialdesignicons-intellisense#20]
Sometime ago VScode made possible to move stuff like the mdi explorer from the file explorer to the sidebar, and MDI explorer doesn't have a icon of its own so it defaults to the some icon file explorer uses.

**Comment by lukas-tr** [comment]
I don't have that much free time right now, but I'll probably fix this within the next few months.
