### ISSUE TITLE
Ability to exclude files/paths from intellisense

### ISSUE THREAD

**Issue by sullyD64** [lukas-tr/vscode-materialdesignicons-intellisense#23]
Thanks for the hard work!
I'm currently using the extension and enjoying it a lot. I think it would be nice to add an option to exclude certain files from checking for icon references to avoid some false negative cases, such as the one I have in this config file for a quasar project:

![immagine](https://user-images.githubusercontent.com/26333714/140894214-17dfa15e-19ad-45c9-ba97-b84dfded09cb.png)

I don't think a prettier/eslint-like disable-by-commenting feature would be useful for this extension, but IMHO the ability to ignore certain files/paths is a fine feature.

**Comment by lukas-tr** [comment]
Good idea, I'll add the option to ignore files.

**Comment by lukas-tr** [comment]
You can ignore paths with `materialdesigniconsIntellisense.linter.ignorePaths` after I publish the new version.
