### ISSUE TITLE
Fail install on VS Code 1.60.0

### ISSUE THREAD

**Issue by 3mta3** [lukas-tr/vscode-materialdesignicons-intellisense#24]
Fyi, manual install on VS Code (docker/latest) fails with the following error:

> Unable to install extension 'lukas-tr.materialdesignicons-intellisense' as it is not compatible with VS Code '1.60.0'.

Downloaded v3.3 and it installed fine though.

**Comment by lukas-tr** [comment]
Seems like your vscode version is slightly behind, the latest stable is 1.62.
