### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by MrMarble** [lukas-tr/vscode-materialdesignicons-intellisense#26]
Hi! Great work with this extension! It is a must if you work with home assistant!

However, it seems the default VS Code package in some distributions is using [OpenVSX](https://open-vsx.org) rather than the VS Marketplace. It would be easier if the extension was available inside VS Code directly on these platforms, too. Would you be interested in providing it on Open VSX, so we can enjoy the extension with convenience? :)

There are a couple of issues related to this https://github.com/microsoft/vscode/issues/107997 https://github.com/microsoft/vscode/issues/108147

**Comment by lukas-tr** [comment]
Thanks for the suggestion, I will look into it.

**Comment by lukas-tr** [comment]
https://open-vsx.org/extension/lukas-tr/materialdesignicons-intellisense
