### ISSUE TITLE
Support of spin / size / flip

### ISSUE THREAD

**Issue by jdmassard** [lukas-tr/vscode-materialdesignicons-intellisense#9]
I've a problem while using intellisense, all works fine but using of classes like: `mdi-24px`, `mdi-spin`, etc ... are marked as not found.

![capture](https://user-images.githubusercontent.com/36268067/66642332-d4816500-ec1c-11e9-815f-3cf50bbf6916.png)

It would be good, if intellisense can detect if it's a size / rotate / spin, etc...
All usable classes are [here](https://cdn.materialdesignicons.com/4.5.95/)

Thanks

**Comment by lukas-tr** [comment]
Those classes are now ignored by the linter.
